on:
  push:
    branches:
      - uat

permissions:
  contents: write
  issues: write
  pull-requests: write

name: release-please-prod

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          release-type: simple
          target-branch: prod
          config-file: release-please-config-prod.json
